services:
  - type: web
    name: document-processing-api
    env: python
    plan: starter
    buildCommand: |
      pip install --no-cache-dir -r requirements.txt  
    startCommand: |
      rm -rf /var/log/*  # Free up log space
      gunicorn app:app --workers 4 --timeout 120  
    healthCheckPath: /api/health
    autoDeploy: true

    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: PYTHONUNBUFFERED
        value: true

    disk:
      name: document-storage
      mountPath: /opt/render/project/src/static
      sizeGB: 5  

    routes:
      - type: rewrite
        source: /static/*
        destination: /static/*
